"""User表增加头像字段

Revision ID: 39c79f190a86
Revises: 
Create Date: 2020-01-19 11:42:16.453457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c79f190a86'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'photo', 'user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'roles_permissions', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'roles_permissions', 'permission', ['permission_id'], ['id'])
    op.add_column('user', sa.Column('avatar_l', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('avatar_m', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('avatar_s', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'avatar_s')
    op.drop_column('user', 'avatar_m')
    op.drop_column('user', 'avatar_l')
    op.drop_constraint(None, 'roles_permissions', type_='foreignkey')
    op.drop_constraint(None, 'roles_permissions', type_='foreignkey')
    op.drop_constraint(None, 'photo', type_='foreignkey')
    # ### end Alembic commands ###
