"""添加图片举报次数统计字段

Revision ID: 7856d094207a
Revises: 39c79f190a86
Create Date: 2020-01-20 16:34:58.805662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7856d094207a'
down_revision = '39c79f190a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('flag', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photo', 'user', ['author_id'], ['id'])
    op.create_foreign_key(None, 'roles_permissions', 'permission', ['permission_id'], ['id'])
    op.create_foreign_key(None, 'roles_permissions', 'role', ['role_id'], ['id'])
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'roles_permissions', type_='foreignkey')
    op.drop_constraint(None, 'roles_permissions', type_='foreignkey')
    op.drop_constraint(None, 'photo', type_='foreignkey')
    op.drop_column('photo', 'flag')
    # ### end Alembic commands ###
